name: 'Get last commit on merged branch'
description: 'Get the last commit that was made on the merged (feature) branch'
inputs:
  none: # id of input, no input
    description: 'no input'
    required: false
    default: ''
outputs:
  commit_hash: # id of output
    description: 'The sha of the last commit on the feature branch'
runs:
  using: 'node12'
  main: 'dist/index.js'
