name: "Update Release"
description: "Update GitHub Release with change log entries"
inputs:
  tags: # id of input, no input
    description: "Array of tags to update"
    required: true
    default: ""
  token:
    description: "github token"
    required: true
    default: ""
  changes:
    description: "changes"
    required: true
    default: ""
runs:
  using: "node12"
  main: "index.js"
