# This is a basic workflow to help you get started with Actions

name: Generate Change Log

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - "*"
    types:
      - "opened"
      - "edited"
      - "reopened"

env:
  BUCKET_NAME: good-ui-static-assets
  NODE_VERSION: 13.3.0
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PROJECT_ID: good-ui

jobs:
  install:
    name: Install Node Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn

  change_log:
    runs-on: ubuntu-latest
    name: Get changes from PR
    needs: [install]
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Pull changes from description
        uses: ./.github/actions/getInfo # Uses an action in the root directory
        id: changeLog
      # Use the output from the `changeLog` step
      - name: Write changes to file
        run: |
          echo "${{ steps.changeLog.outputs.changes }}" > .github/changeLog/log.txt
      - uses: actions/upload-artifact@v1
        with:
          name: change-log
          path: .github/changeLog/log.txt

  upload:
    name: Upload Change Log to GCP
    runs-on: ubuntu-latest
    needs: [change_log]
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "285.0.0"
          project_id: "good-ui"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/download-artifact@v1
        with:
          name: change-log
      - name: GCP Upload
        run: |
          if [ "${{ github.head_ref }}" == "master" ]; then
            gsutil -m rsync -r -c change-log gs://$BUCKET_NAME/test/
          else
            gsutil -m rsync -r -c change-log gs://$BUCKET_NAME/test/${{ github.head_ref }}
          fi
