# This workflow generates a change log based on PR title and description
# and pushes that log to google cloud storage
name: Generate Change Log

# Runs on pull_request open, edit, reopen, and synchronize (commit push to branch) events
on:
  pull_request:
    branches:
      - "*"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"

env:
  BUCKET_NAME: good-ui-static-assets
  NODE_VERSION: 13.3.0
  BRANCH_ID: ${{ github.event.pull_request.head.sha }}

jobs:
  change_log:
    runs-on: ubuntu-latest
    name: Get changes from PR
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull changes from description
        uses: ./.github/actions/get-logs # Uses an action in the root directory
        id: changeLog
      # Use the output from the `changeLog` step
      - name: Write changes to file
        run: |
          echo "${{ steps.changeLog.outputs.changes }}" > .github/log.json
      - uses: actions/upload-artifact@v1
        with:
          name: change-log
          path: .github/log.json

  upload:
    name: Upload Change Log to GCP
    runs-on: ubuntu-latest
    needs: [change_log]
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "285.0.0"
          project_id: "good-ui"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/download-artifact@v1
        with:
          name: change-log
      - run: echo "$BRANCH_ID"
      - name: GCP Upload
        run: gsutil -m rsync -r -c change-log gs://$BUCKET_NAME/changeLogs/$BRANCH_ID
