# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

env:
  BUCKET_NAME: good-ui-static-assets
  NODE_VERSION: 13.3.0
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PROJECT_ID: good-ui

jobs:
  install:
    name: Install Node Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn

  download:
    name: Grab Change Log from GCP
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "285.0.0"
          project_id: "good-ui"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: GCP download
        run: |
          gsutil cp gs://$BUCKET_NAME/test/bump/log.txt .
      - uses: actions/upload-artifact@v1
        with:
          name: change-log
          path: ./log.txt

  publish:
    name: Publish Lerna Packages
    needs: [install, download]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Configure CI Git User
        run: |
          git config --global user.name 'ekohanyi'
          git config --global user.email 'emmajk2012@gmail.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/ekohanyi/github-packages-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@master
        with:
          node-version: 13.3.0
          registry-url: https://npm.pkg.github.com/
          scope: "@ekohanyi"
      - name: Restore Cache
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Build
        run: yarn build
      - uses: actions/download-artifact@v1
        with:
          name: change-log
      - name: Get version
        id: version
        run: |
          value=$(cat change-log/log.txt | jq -r .bump)
          echo The result is $value
          echo ::set-output name=version::${value}
      - name: Publish to GitHub Package Registry
        run: |
          git reset --hard master
          yarn lerna publish ${{ steps.version.outputs.version }} \
          --registry "https://npm.pkg.github.com/" \
          --yes \
          --no-verify-access \
          --force-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fun_with_tags:
    name: Fun with tags
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Configure CI Git User
        run: |
          git config --global user.name 'ekohanyi'
          git config --global user.email 'emmajk2012@gmail.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/ekohanyi/github-packages-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get packages that changed
        run: |
          git pull
          commit=$(echo `git log --format="%H" -n 1`)
          echo $commit
          echo $(git ls-remote --tags | grep $commit)
