# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 13.3.0
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PROJECT_ID: good-ui

jobs:
  install:
    name: Install Node Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn

  # download:
  #   name: Grab Change Log from GCP
  #   runs-on: ubuntu-latest
  #   needs: [install]
  #   steps:
  #     - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  #       with:
  #         version: '285.0.0'
  #         project_id: 'good-ui'
  #         service_account_email: ${{ secrets.GCP_SA_EMAIL }}
  #         service_account_key: ${{ secrets.GCP_SA_KEY }}
  #         export_default_credentials: true
  #     - name: GCP download
  #       run: |
  #         if [ "${{ github.head_ref }}" == "master" ]; then
  #           gsutil cp gs://$BUCKET_NAME/log.txt .
  #         else
  #           gsutil cp gs://$BUCKET_NAME/${{ github.head_ref }}/log.txt .
  #         fi
  #     - name: Read log.txt
  #       id: log
  #       uses: juliangruber/read-file-action@v1
  #       with:
  #         path: ./log.txt
  #     - name: Echo log.txt
  #       run: echo ${{ steps.log.outputs.content }}

  publish:
    name: Publish Lerna Packages
    needs: [install]
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 13.3.0
          registry-url: https://npm.pkg.github.com/
          scope: "@ekohanyi"
      - name: Restore Cache
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish to GitHub Package Registry
        run: |
          git checkout pub/release
          yarn lerna publish \
          --registry "https://npm.pkg.github.com/" \
          --git-remote release \
          --yes \
          --no-verify-access \
          --exact \
          --force-publish \
          --preid "${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
