# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - "*"

env:
  BUCKET_NAME: good-ui-static-assets
  NODE_VERSION: 13.3.0
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PROJECT_ID: good-ui

jobs:
  install:
    name: Install Node Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: |
          yarn
          echo ${{ github }}

  download:
    name: Grab Change Log from GCP
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "285.0.0"
          project_id: "good-ui"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: GCP download
        run: |
          gsutil cp gs://$BUCKET_NAME/test/bump/log.txt .
      - uses: actions/upload-artifact@v1
        with:
          name: change-log
          path: ./log.txt
  # fun_with_tags:
  #   name: Fun with tags
  #   needs: [publish]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         # pulls all commits (needed for lerna / semantic release to correctly version)
  #         fetch-depth: "0"
  #     # pulls all tags (needed for lerna / semantic release to correctly version)
  #     - run: git fetch --depth=1 origin
  #     - name: Configure CI Git User
  #       run: |
  #         git config --global user.name 'ekohanyi'
  #         git config --global user.email 'emmajk2012@gmail.com'
  #         git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/ekohanyi/github-packages-publish
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Get packages that changed
  #       run: |
  #         git log -n 1 --pretty=format:"%H"
  #         commit=$(echo `git log --format="%H" -n 1`)
  #         echo $commit
  #         echo $(git ls-remote --tags | grep $commit)
